extends RefCounted

const DEBUG = false
const DISPLAY_VELOCITY = false
const DISPLAY_FORCE = true

const WIDTH = 400
const HEIGHT = 200
const SCALE = 3
const RENDER_WIDTH = WIDTH * SCALE
const RENDER_HEIGHT = HEIGHT * SCALE

const NUMBER_PARTICLES = 50

const GRAVITY = 10

const INTERACTION_RADIUS = 10.0
const SPRING_CONSTANT = GRAVITY / INTERACTION_RADIUS
