extends RefCounted

const DEBUG = false
const DISPLAY_VELOCITY = false
const DISPLAY_FORCE = true

const WIDTH = 1920
const HEIGHT = 1080
const SCALE = 1
const RENDER_WIDTH = WIDTH * SCALE
const RENDER_HEIGHT = HEIGHT * SCALE

const NUMBER_PARTICLES = 2

const GRAVITY = 100

const INTERACTION_RADIUS = 10.0
const SPRING_CONSTANT = GRAVITY / INTERACTION_RADIUS

const PARTICLE_SIZE = 2
